<?php

$metrikaGoalIdsField = [
    'key' => 'goal_ids',
    'label' => 'Цели в отчёте',
    'type' => 'multiselect',
    'default' => [],
    'options_key' => 'metrika_goals',
];

$metrikaTrafficSourceField = [
    'key' => 'traffic_source',
    'label' => 'Канал конверсии',
    'type' => 'select',
    'default' => '',
    'options_key' => 'metrika_traffic_sources',
];

return [
    'blocks' => [
        [
            'block_type' => 'title_page',
            'category' => 'general',
            'label' => 'Титульная страница',
            'description' => 'Название проекта, период отчёта, логотип',
            'required_integration' => null,
            'dashboard_eligible' => false,
        ],
        [
            'block_type' => 'table_of_contents',
            'category' => 'general',
            'label' => 'Содержание',
            'description' => 'Оглавление с разделами отчёта',
            'required_integration' => null,
            'dashboard_eligible' => false,
        ],
        [
            'block_type' => 'text_block',
            'category' => 'general',
            'label' => 'Текстовый блок',
            'description' => 'Произвольный текст или комментарии',
            'required_integration' => null,
            'dashboard_eligible' => false,
            'settings_schema' => [
                ['key' => 'title', 'label' => 'Заголовок', 'type' => 'text', 'default' => 'Комментарии'],
                ['key' => 'content', 'label' => 'Текст', 'type' => 'textarea', 'default' => 'Раздел для ручных комментариев специалиста.'],
            ],
        ],
        [
            'block_type' => 'metrika_overview',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: обзор',
            'description' => 'Визиты, пользователи, отказы, время на сайте',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_traffic_sources',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: источники трафика',
            'description' => 'Каналы и источники посещений',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_goals',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: цели',
            'description' => 'Достижение целей и конверсии',
            'required_integration' => 'yandex_metrika',
            'settings_schema' => [
                $metrikaGoalIdsField,
                $metrikaTrafficSourceField,
            ],
        ],
        [
            'block_type' => 'metrika_devices',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: устройства',
            'description' => 'Распределение визитов по типам устройств',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_geo',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: география',
            'description' => 'География посетителей',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_daily_visits',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: динамика по дням',
            'description' => 'Визиты за каждый день отчётного периода',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_monthly_visits',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: динамика по месяцам',
            'description' => 'Визиты за последние 12 месяцев',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_search_engines',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: поисковые системы',
            'description' => 'Распределение органического трафика по ПС',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_search_engines_timeline',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: ПС — динамика 13 мес.',
            'description' => 'Органический трафик по поисковым системам за год и месяц до конца отчёта',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_organic_daily',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: поисковый трафик по дням',
            'description' => 'Органический трафик по дням с сравнением периодов',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_landing_pages',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: посадочные страницы',
            'description' => 'Популярные страницы входа',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_high_bounce',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: высокий отказ',
            'description' => 'Страницы с высоким показателем отказов',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_conversions_by_source',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: конверсии по каналам',
            'description' => 'Достижения целей по источникам трафика',
            'required_integration' => 'yandex_metrika',
            'settings_schema' => [
                $metrikaGoalIdsField,
            ],
        ],
        [
            'block_type' => 'ga_overview',
            'category' => 'google_analytics',
            'label' => 'GA4: обзор',
            'description' => 'Сессии, пользователи, вовлечённость',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'ga_channels',
            'category' => 'google_analytics',
            'label' => 'GA4: каналы',
            'description' => 'Каналы привлечения трафика',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'ga_devices',
            'category' => 'google_analytics',
            'label' => 'GA4: устройства',
            'description' => 'Распределение сессий по типам устройств',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'ga_geo',
            'category' => 'google_analytics',
            'label' => 'GA4: география',
            'description' => 'География сессий',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'ga_landing_pages',
            'category' => 'google_analytics',
            'label' => 'GA4: посадочные страницы',
            'description' => 'Популярные страницы входа',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'gsc_top_queries',
            'category' => 'google_search_console',
            'label' => 'GSC: топ запросов',
            'description' => 'Популярные поисковые запросы Google',
            'required_integration' => 'google_search_console',
        ],
        [
            'block_type' => 'gsc_performance',
            'category' => 'google_search_console',
            'label' => 'GSC: эффективность в поиске',
            'description' => 'Сводка кликов, показов и CTR',
            'required_integration' => 'google_search_console',
        ],
        [
            'block_type' => 'gsc_top_pages',
            'category' => 'google_search_console',
            'label' => 'GSC: топ посадочных страниц',
            'description' => 'Страницы с наибольшим числом кликов из Google',
            'required_integration' => 'google_search_console',
        ],
        [
            'block_type' => 'webmaster_queries',
            'category' => 'yandex_webmaster',
            'label' => 'Вебмастер: запросы',
            'description' => 'Поисковые запросы и клики в Яндексе',
            'required_integration' => 'yandex_webmaster',
        ],
        [
            'block_type' => 'webmaster_search_summary',
            'category' => 'yandex_webmaster',
            'label' => 'Вебмастер: эффективность в поиске',
            'description' => 'Сводка показов, кликов и CTR',
            'required_integration' => 'yandex_webmaster',
        ],
        [
            'block_type' => 'webmaster_sqi_history',
            'category' => 'yandex_webmaster',
            'label' => 'Вебмастер: история ИКС',
            'description' => 'Динамика индекса качества сайта',
            'required_integration' => 'yandex_webmaster',
        ],
        [
            'block_type' => 'webmaster_indexing_history',
            'category' => 'yandex_webmaster',
            'label' => 'Вебмастер: история индексации',
            'description' => 'Динамика проиндексированных страниц (HTTP 2xx)',
            'required_integration' => 'yandex_webmaster',
        ],
        [
            'block_type' => 'wordstat_dynamics',
            'category' => 'yandex_wordstat',
            'label' => 'Вордстат: динамика спроса',
            'description' => 'График частотности запросов. Фразы задаются в настройках проекта.',
            'required_integration' => 'yandex_wordstat',
        ],
        [
            'block_type' => 'wordstat_top_requests',
            'category' => 'yandex_wordstat',
            'label' => 'Вордстат: популярные запросы',
            'description' => 'Топ связанных запросов за 30 дней. Фраза задаётся в настройках проекта.',
            'required_integration' => 'yandex_wordstat',
        ],
        [
            'block_type' => 'wordstat_regions',
            'category' => 'yandex_wordstat',
            'label' => 'Вордстат: регионы',
            'description' => 'Распределение запросов по регионам. Фраза задаётся в настройках проекта.',
            'required_integration' => 'yandex_wordstat',
        ],
        [
            'block_type' => 'search_clicks_compare',
            'category' => 'cross_analytics',
            'label' => 'Сравнение: Яндекс vs Google',
            'description' => 'Клики и CTR в поиске двух систем',
            'required_integration' => null,
        ],
        [
            'block_type' => 'work_performed',
            'category' => 'general',
            'label' => 'Проделанная работа',
            'description' => 'Список выполненных работ за период отчёта',
            'required_integration' => null,
            'dashboard_eligible' => false,
        ],
        [
            'block_type' => 'positions_visibility',
            'category' => 'positions',
            'label' => 'Позиции: видимость',
            'description' => 'Видимость сайта и средняя позиция (Topvisor или Keys.so)',
            'required_integration' => null,
        ],
        [
            'block_type' => 'positions_top_distribution',
            'category' => 'positions',
            'label' => 'Позиции: TOP-N',
            'description' => 'Распределение по ТОПам (1–3, 1–10, 11–30, 31–50, 51–100, 100+) с долей и динамикой',
            'required_integration' => null,
        ],
        [
            'block_type' => 'positions_table',
            'category' => 'positions',
            'label' => 'Позиции: таблица ключей',
            'description' => 'Ключевые фразы с позициями и динамикой',
            'required_integration' => null,
            'settings_schema' => [
                ['key' => 'limit', 'label' => 'Количество ключей', 'type' => 'number', 'default' => 50, 'min' => 1, 'max' => 200],
            ],
        ],
        [
            'block_type' => 'keys_so_site_queries',
            'category' => 'keys_so',
            'label' => 'Keys.so: запросы сайта',
            'description' => 'Сводка по запросам сайта (топы и ИИ) и превью органической выдачи, как в дашборде Keys.so',
            'required_integration' => 'keys_so',
            'settings_schema' => [
                [
                    'key' => 'base',
                    'label' => 'Региональная база',
                    'type' => 'select',
                    'default' => 'msk',
                    'options' => [
                        ['value' => 'msk', 'label' => 'Яндекс: Москва'],
                        ['value' => 'spb', 'label' => 'Яндекс: Санкт-Петербург'],
                        ['value' => 'gru', 'label' => 'Google: Москва'],
                        ['value' => 'gny', 'label' => 'Google: New York'],
                    ],
                ],
                ['key' => 'limit', 'label' => 'Запросов в таблице «Органическая выдача»', 'type' => 'number', 'default' => 10, 'min' => 1, 'max' => 50],
            ],
        ],
        [
            'block_type' => 'keys_so_links',
            'category' => 'keys_so',
            'label' => 'Keys.so: ссылки',
            'description' => 'Сводка по ссылочному профилю домена, как в дашборде Keys.so',
            'required_integration' => 'keys_so',
            'settings_schema' => [],
        ],
        [
            'block_type' => 'keys_so_ai_mentions',
            'category' => 'keys_so',
            'label' => 'Keys.so: упоминания в ИИ',
            'description' => 'Запросы, по которым сайт упоминается в ИИ-ответах Яндекса',
            'required_integration' => 'keys_so',
            'settings_schema' => [
                ['key' => 'limit', 'label' => 'Количество строк', 'type' => 'number', 'default' => 25, 'min' => 1, 'max' => 100],
            ],
        ],
    ],

    'categories' => [
        'general' => 'Общие',
        'yandex_metrika' => 'Яндекс.Метрика',
        'google_analytics' => 'Google Analytics',
        'google_search_console' => 'Search Console',
        'yandex_webmaster' => 'Яндекс.Вебмастер',
        'yandex_wordstat' => 'Яндекс Вордстат',
        'cross_analytics' => 'Сводная аналитика',
        'positions' => 'Позиции (Topvisor)',
        'keys_so' => 'Keys.so',
    ],

    'default_template' => [
        'name' => 'Стандартный SEO-отчёт',
        'description' => 'Базовый шаблон с титульной страницей и блоками аналитики',
        'blocks' => [
            'title_page',
            'table_of_contents',
            'metrika_overview',
            'metrika_traffic_sources',
            'text_block',
        ],
    ],
];
