<?php

return [
    'blocks' => [
        [
            'block_type' => 'title_page',
            'category' => 'general',
            'label' => 'Титульная страница',
            'description' => 'Название проекта, период отчёта, логотип',
            'required_integration' => null,
        ],
        [
            'block_type' => 'table_of_contents',
            'category' => 'general',
            'label' => 'Содержание',
            'description' => 'Оглавление с разделами отчёта',
            'required_integration' => null,
        ],
        [
            'block_type' => 'text_block',
            'category' => 'general',
            'label' => 'Текстовый блок',
            'description' => 'Произвольный текст или комментарии',
            'required_integration' => null,
        ],
        [
            'block_type' => 'metrika_overview',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: обзор',
            'description' => 'Визиты, пользователи, отказы, время на сайте',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_traffic_sources',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: источники трафика',
            'description' => 'Каналы и источники посещений',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_goals',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: цели',
            'description' => 'Достижение целей и конверсии',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_devices',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: устройства',
            'description' => 'Распределение визитов по типам устройств',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_geo',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: география',
            'description' => 'География посетителей',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_daily_visits',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: динамика по дням',
            'description' => 'Визиты за каждый день отчётного периода',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_monthly_visits',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: динамика по месяцам',
            'description' => 'Визиты за последние 12 месяцев',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_search_engines',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: поисковые системы',
            'description' => 'Распределение органического трафика по ПС',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_organic_daily',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: поисковый трафик по дням',
            'description' => 'Органический трафик по дням с сравнением периодов',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_landing_pages',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: посадочные страницы',
            'description' => 'Популярные страницы входа',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_high_bounce',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: высокий отказ',
            'description' => 'Страницы с высоким показателем отказов',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'metrika_conversions_by_source',
            'category' => 'yandex_metrika',
            'label' => 'Метрика: конверсии по каналам',
            'description' => 'Достижения целей по источникам трафика',
            'required_integration' => 'yandex_metrika',
        ],
        [
            'block_type' => 'ga_overview',
            'category' => 'google_analytics',
            'label' => 'GA4: обзор',
            'description' => 'Сессии, пользователи, вовлечённость',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'ga_channels',
            'category' => 'google_analytics',
            'label' => 'GA4: каналы',
            'description' => 'Каналы привлечения трафика',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'ga_devices',
            'category' => 'google_analytics',
            'label' => 'GA4: устройства',
            'description' => 'Распределение сессий по типам устройств',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'ga_geo',
            'category' => 'google_analytics',
            'label' => 'GA4: география',
            'description' => 'География сессий',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'ga_landing_pages',
            'category' => 'google_analytics',
            'label' => 'GA4: посадочные страницы',
            'description' => 'Популярные страницы входа',
            'required_integration' => 'google_analytics',
        ],
        [
            'block_type' => 'gsc_top_queries',
            'category' => 'google_search_console',
            'label' => 'GSC: топ запросов',
            'description' => 'Популярные поисковые запросы Google',
            'required_integration' => 'google_search_console',
        ],
        [
            'block_type' => 'gsc_performance',
            'category' => 'google_search_console',
            'label' => 'GSC: эффективность в поиске',
            'description' => 'Сводка кликов, показов и CTR',
            'required_integration' => 'google_search_console',
        ],
        [
            'block_type' => 'gsc_top_pages',
            'category' => 'google_search_console',
            'label' => 'GSC: топ посадочных страниц',
            'description' => 'Страницы с наибольшим числом кликов из Google',
            'required_integration' => 'google_search_console',
        ],
        [
            'block_type' => 'webmaster_queries',
            'category' => 'yandex_webmaster',
            'label' => 'Вебмастер: запросы',
            'description' => 'Поисковые запросы и клики в Яндексе',
            'required_integration' => 'yandex_webmaster',
        ],
        [
            'block_type' => 'webmaster_search_summary',
            'category' => 'yandex_webmaster',
            'label' => 'Вебмастер: эффективность в поиске',
            'description' => 'Сводка показов, кликов и CTR',
            'required_integration' => 'yandex_webmaster',
        ],
        [
            'block_type' => 'webmaster_sqi_history',
            'category' => 'yandex_webmaster',
            'label' => 'Вебмастер: история ИКС',
            'description' => 'Динамика индекса качества сайта',
            'required_integration' => 'yandex_webmaster',
        ],
        [
            'block_type' => 'webmaster_indexing_history',
            'category' => 'yandex_webmaster',
            'label' => 'Вебмастер: история индексации',
            'description' => 'Количество страниц в поиске Яндекса',
            'required_integration' => 'yandex_webmaster',
        ],
        [
            'block_type' => 'search_clicks_compare',
            'category' => 'cross_analytics',
            'label' => 'Сравнение: Яндекс vs Google',
            'description' => 'Клики и CTR в поиске двух систем',
            'required_integration' => null,
        ],
        [
            'block_type' => 'work_performed',
            'category' => 'general',
            'label' => 'Проделанная работа',
            'description' => 'Список выполненных работ за период отчёта',
            'required_integration' => null,
        ],
        [
            'block_type' => 'positions_visibility',
            'category' => 'positions',
            'label' => 'Позиции: видимость',
            'description' => 'Видимость сайта и средняя позиция из Topvisor',
            'required_integration' => 'topvisor',
        ],
        [
            'block_type' => 'positions_top_distribution',
            'category' => 'positions',
            'label' => 'Позиции: TOP-N',
            'description' => 'Распределение ключей по TOP-3/10/30/100',
            'required_integration' => 'topvisor',
        ],
        [
            'block_type' => 'positions_table',
            'category' => 'positions',
            'label' => 'Позиции: таблица ключей',
            'description' => 'Ключевые фразы с позициями и динамикой',
            'required_integration' => 'topvisor',
        ],
    ],

    'categories' => [
        'general' => 'Общие',
        'yandex_metrika' => 'Яндекс.Метрика',
        'google_analytics' => 'Google Analytics',
        'google_search_console' => 'Search Console',
        'yandex_webmaster' => 'Яндекс.Вебмастер',
        'cross_analytics' => 'Сводная аналитика',
        'positions' => 'Позиции (Topvisor)',
    ],

    'default_template' => [
        'name' => 'Стандартный SEO-отчёт',
        'description' => 'Базовый шаблон с титульной страницей и блоками аналитики',
        'blocks' => [
            'title_page',
            'table_of_contents',
            'metrika_overview',
            'metrika_traffic_sources',
            'text_block',
        ],
    ],
];
